"""Initial complete schema with all models

Revision ID: 064209575e5d
Revises: 
Create Date: 2025-11-07 22:08:02.118364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064209575e5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la categoría'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre visible de la categoría'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identificador único legible en URLs'),
    sa.Column('type', sa.Enum('MATERIAL', 'PRODUCT', name='listing_type_enum', create_constraint=True), nullable=False, comment='Tipo de categoría: MATERIAL o PRODUCT'),
    sa.Column('parent_category_id', sa.Integer(), nullable=True, comment='ID de categoría padre para jerarquías'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('ix_categories_name_type', 'categories', ['name', 'type'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_index('ix_categories_type_parent', 'categories', ['type', 'parent_category_id'], unique=False)
    op.create_table('faq_items',
    sa.Column('faq_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del item de FAQ'),
    sa.Column('category', sa.String(length=100), server_default=sa.text("'General'"), nullable=True, comment='Categoría o tema de la pregunta frecuente'),
    sa.Column('question', sa.Text(), nullable=False, comment='Texto de la pregunta frecuente'),
    sa.Column('answer', sa.Text(), nullable=False, comment='Texto de la respuesta a la pregunta'),
    sa.Column('display_order', sa.SmallInteger(), nullable=True, comment='Orden de visualización del item en la lista de FAQs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('legal_documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador unico del documento legal'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="Indentificador amigable para URLs (ej: 'terms-of-service)"),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Titulo del documento legal'),
    sa.Column('content', sa.Text(), nullable=False, comment='Contenido completo del documento legal'),
    sa.Column('version', sa.Float(), server_default='1.0', nullable=False, comment='Numero de version del documento (ej: 1.0, 1.1)'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del documento'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del plan'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre del plan de suscripción'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio del plan'),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), nullable=False, comment='Ciclo de facturación: monthly, quarterly o yearly'),
    sa.Column('features_json', sa.String(), nullable=True, comment='Características y límites del plan en formato JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario (cognito sub claim)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Correo electrónico del usuario (debe ser normalizado)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Nombre completo o visible del usuario'),
    sa.Column('bio', sa.String(length=1000), nullable=True, comment='Biografía del vendedor - información pública sobre el negocio'),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role_enum', create_constraint=True), nullable=False, comment='Rol del usuario en la plataforma'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', name='user_status_enum', create_constraint=True), nullable=False, comment='Estado actual del usuario'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la dirección'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='UUID del usuario propietario (NULL para direcciones de listings sin usuario)'),
    sa.Column('street', sa.String(length=255), nullable=False, comment='Calle y número'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Ciudad o municipio'),
    sa.Column('state', sa.String(length=100), nullable=False, comment='Estado, provincia o región'),
    sa.Column('postal_code', sa.String(length=20), nullable=False, comment='Código postal'),
    sa.Column('country', sa.String(length=2), nullable=False, comment='Código de país ISO 3166-1 alpha-2 (ej: MX, US, CA)'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Referencias adicionales, indicaciones de ubicación'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Indica si es la dirección predeterminada del usuario'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name='ck_address_country_iso_format'),
    sa.CheckConstraint('length(postal_code) >= 4', name='ck_address_postal_code_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('admin_action_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador unico del log de accion administrativa'),
    sa.Column('admin_id', sa.UUID(), nullable=True, comment='UUID del administrador que ejecutó la acción'),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment='Tipo de accion admnistrativa realizada'),
    sa.Column('target_entity_type', sa.String(length=50), nullable=True, comment='Tipo de entidad afectada por la accion (ej. LISTING_REJECTED, REPORT_RESOLVED, USR_BLOCKED)'),
    sa.Column('target_entity_id', sa.Integer(), nullable=True, comment='ID de la entidad afectada'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Razon o descripcion detallada de la accion admnistrativa'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora en que se registro la accion'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del carrito'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario propietario del carrito (relación 1:1)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la notificación'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario que recibe la notificación'),
    sa.Column('content', sa.Text(), nullable=False, comment='Texto del mensaje de la notificación'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='Categoría de la notificación (ORDER, REPORT_RESOLVED, OFFER, etc.)'),
    sa.Column('link_url', sa.String(length=512), nullable=True, comment="URL relativa de destino al hacer clic (ej. '/my-offers/123')"),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Indica si el usuario ya vio/leyó esta notificación'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Nivel de prioridad: LOW, MEDIUM, HIGH'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la orden'),
    sa.Column('buyer_id', sa.UUID(), nullable=False, comment='UUID del usuario comprador que realizó la orden'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Suma de los precios de todos los items sin comisión (precisión de 2 decimales)'),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Comisión de la plataforma, 10% del subtotal (precisión de 2 decimales)'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto total pagado: subtotal + commission_amount (precisión de 2 decimales)'),
    sa.Column('order_status', sa.Enum('PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status_enum', create_constraint=True), nullable=False, comment='Estado actual de la orden: PAID, SHIPPED, DELIVERED, CANCELLED, REFUNDED'),
    sa.Column('payment_charge_id', sa.String(length=255), nullable=True, comment='ID de la transacción en la pasarela de pago (Stripe/PayPal)'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment="Método de pago utilizado: 'stripe' o 'paypal'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('payment_charge_id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index('ix_orders_buyer_status', 'orders', ['buyer_id', 'order_status'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_table('payment_customers',
    sa.Column('payment_customer_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del registro de customer'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario propietario'),
    sa.Column('gateway', sa.Enum('STRIPE', name='payment_gateway_enum', create_constraint=True), nullable=False, comment='Pasarela de pago: STRIPE o PAYPAL'),
    sa.Column('gateway_customer_id', sa.String(length=255), nullable=False, comment='ID único del customer en la pasarela (cus_xxx para Stripe)'),
    sa.Column('default_payment_method_id', sa.String(length=255), nullable=True, comment='ID del método de pago predeterminado (pm_xxx para Stripe)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_customer_id'),
    sa.UniqueConstraint('gateway_customer_id'),
    sa.UniqueConstraint('user_id', 'gateway', name='uq_payment_customer_user_gateway')
    )
    op.create_index('ix_payment_customers_user_gateway', 'payment_customers', ['user_id', 'gateway'], unique=False)
    op.create_index(op.f('ix_payment_customers_user_id'), 'payment_customers', ['user_id'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('method_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único para el método de envío.'),
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='UUID del vendedor que ofrece este método.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Nombre descriptivo (ej. 'Recojo en taller')."),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='El precio que será agregado a la orden si este método es escogido.'),
    sa.Column('type', sa.Enum('PICKUP', 'DELIVERY', name='shipping_type_enum', create_constraint=True), nullable=False, comment="Define si es para recojo ('pickup') o para envío a casa ('delivery')."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la Suscripción'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario suscrito'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='Llave foranea a la tabla de planes (plans)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', name='subscription_status_enum', create_constraint=True), nullable=False, comment='Estatus actual de la suscripcion (e.g., ACTIVE, INACTIVE, CANCELLED).'),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de inicio de la suscripcion'),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False, comment='Fecha del proximo cobro de la suscripcion'),
    sa.Column('gateway_sub_id', sa.String(length=255), nullable=False, comment='ID unico de la suscripcion en la pasarela de pago'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('gateway_sub_id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='unique_user_plan')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la publicación'),
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='UUID del usuario vendedor que creó esta publicación'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='ID de la categoría a la que pertenece'),
    sa.Column('listing_type', sa.Enum('MATERIAL', 'PRODUCT', name='listing_type_enum'), nullable=False, comment='Tipo de publicación: MATERIAL (B2B) o PRODUCT (B2C)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título visible de la publicación'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descripción detallada del material o producto'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio monetario del ítem (precisión de 2 decimales)'),
    sa.Column('price_unit', sa.String(length=50), nullable=True, comment="Unidad de precio (ej. 'Kg', 'Tonelada', 'Unidad', 'Lote')"),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad disponible en inventario (stock)'),
    sa.Column('location_address_id', sa.Integer(), nullable=True, comment='ID de la dirección donde se encuentra el ítem físicamente'),
    sa.Column('origin_description', sa.Text(), nullable=True, comment='Descripción del origen reciclado o reutilizado del material'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'INACTIVE', name='listing_status_enum', create_constraint=True), nullable=False, comment='Estado de moderación: PENDING, ACTIVE, REJECTED, INACTIVE'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Razón por la cual la publicación fue rechazada (proporcionada por admin)'),
    sa.Column('approved_by_admin_id', sa.UUID(), nullable=True, comment='UUID del administrador que aprobó la publicación'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_address_id'], ['addresses.address_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_index('ix_listings_category_status', 'listings', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_listings_listing_type'), 'listings', ['listing_type'], unique=False)
    op.create_index('ix_listings_price', 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_index('ix_listings_seller_status', 'listings', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index('ix_listings_type_status', 'listings', ['listing_type', 'status'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la transacción de pago'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='ID de la orden asociada (NULL para subscriptions)'),
    sa.Column('subscription_id', sa.Integer(), nullable=True, comment='ID de la suscripción asociada (NULL para orders)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID del usuario que realizó el pago'),
    sa.Column('gateway', sa.Enum('STRIPE', name='payment_gateway_enum', create_constraint=True), nullable=False, comment='Pasarela de pago utilizada: STRIPE o PAYPAL'),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=False, comment='ID único de la transacción en la pasarela (ch_xxx, pi_xxx, PAYID-xxx)'),
    sa.Column('gateway_customer_id', sa.String(length=255), nullable=True, comment='ID del customer en la pasarela (cus_xxx para Stripe)'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto total pagado (precisión de 2 decimales)'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Código de moneda ISO 4217 (MXN, USD, etc)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', name='payment_status_enum', create_constraint=True), nullable=False, comment='Estado actual de la transacción'),
    sa.Column('payment_method_type', sa.String(length=50), nullable=True, comment='Tipo de método de pago (card, oxxo, spei, paypal, etc)'),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True, comment='Últimos 4 dígitos del método de pago (tarjetas)'),
    sa.Column('payment_method_brand', sa.String(length=50), nullable=True, comment='Marca del método de pago (visa, mastercard, amex, etc)'),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de inicio de la transacción'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de completado exitoso (NULL si no completado)'),
    sa.Column('error_code', sa.String(length=100), nullable=True, comment='Código de error de la pasarela si la transacción falló'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Mensaje de error detallado para debugging'),
    sa.Column('transaction_metadata', sa.Text(), nullable=True, comment='JSON con metadata adicional de la transacción'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint('(order_id IS NOT NULL AND subscription_id IS NULL) OR (order_id IS NULL AND subscription_id IS NOT NULL)', name='check_transaction_type_exclusive'),
    sa.CheckConstraint('amount > 0', name='check_payment_amount_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('gateway_transaction_id')
    )
    op.create_index('ix_payment_transactions_created', 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_gateway'), 'payment_transactions', ['gateway'], unique=False)
    op.create_index('ix_payment_transactions_gateway_status', 'payment_transactions', ['gateway', 'status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_subscription_id'), 'payment_transactions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_index('ix_payment_transactions_user_status', 'payment_transactions', ['user_id', 'status'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del item del carrito'),
    sa.Column('cart_id', sa.Integer(), nullable=False, comment='Carrito al que pertenece este item'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Listing (producto/material) agregado al carrito'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad de unidades seleccionadas'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint('quantity > 0', name='ck_cart_item_quantity_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cart_item_id'),
    sa.UniqueConstraint('cart_id', 'listing_id', name='uq_cart_item_cart_listing')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index('ix_cart_items_cart_listing', 'cart_items', ['cart_id', 'listing_id'], unique=False)
    op.create_index(op.f('ix_cart_items_listing_id'), 'cart_items', ['listing_id'], unique=False)
    op.create_table('listing_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la imagen'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='ID de la publicación a la que pertenece esta imagen'),
    sa.Column('image_url', sa.String(length=512), nullable=False, comment='URL completa y pública del objeto en el bucket S3'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Indica si esta es la imagen principal/portada del listing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_listing_images_listing_id'), 'listing_images', ['listing_id'], unique=False)
    op.create_index('ix_listing_images_listing_primary', 'listing_images', ['listing_id', 'is_primary'], unique=True, postgresql_where='is_primary = true')
    op.create_table('listing_shipping_options',
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='ID del listing al que aplica esta opción de envío'),
    sa.Column('method_id', sa.Integer(), nullable=False, comment='ID del método de envío disponible para este listing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['shipping_methods.method_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'method_id'),
    comment='Tabla pivote que conecta listings con métodos de envío disponibles'
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la oferta'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='ID del listing (material) sobre el que se hace la oferta'),
    sa.Column('buyer_id', sa.UUID(), nullable=False, comment='UUID del usuario comprador que envía la oferta'),
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='UUID del usuario vendedor que recibe la oferta'),
    sa.Column('offer_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio unitario propuesto por el comprador (precisión de 2 decimales)'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Número de unidades que el comprador desea adquirir'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'EXPIRED', name='offer_status_enum', create_constraint=True), nullable=False, comment='Estado de la negociación: PENDING, ACCEPTED, REJECTED, COUNTERED, EXPIRED'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp opcional de expiración automática si el vendedor no responde'),
    sa.Column('counter_offer_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Precio unitario de contraoferta propuesto por el vendedor'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment='Motivo opcional del rechazo por parte del vendedor'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_offers_buyer_id'), 'offers', ['buyer_id'], unique=False)
    op.create_index('ix_offers_buyer_status', 'offers', ['buyer_id', 'status'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    op.create_index('ix_offers_listing_status', 'offers', ['listing_id', 'status'], unique=False)
    op.create_index(op.f('ix_offers_seller_id'), 'offers', ['seller_id'], unique=False)
    op.create_index('ix_offers_seller_status', 'offers', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del ítem de la orden'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='ID de la orden a la que pertenece este ítem'),
    sa.Column('listing_id', sa.Integer(), nullable=True, comment='ID del listing (producto/material) asociado. Nulo si el listing fue eliminado.'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad del ítem comprado'),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio unitario del ítem en el momento de la compra (precisión de 2 decimales)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del reporte'),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False, comment='UUID del usuario que reporta'),
    sa.Column('report_type', sa.Enum('LISTING', 'USER', 'ORDER', name='report_type_enum'), nullable=False, comment='Tipo de reporte: listing, user u order'),
    sa.Column('reported_listing_id', sa.Integer(), nullable=True, comment='Llave foránea a listings (si se reporta un listing)'),
    sa.Column('reported_user_id', sa.UUID(), nullable=True, comment='UUID del usuario reportado (si se reporta un usuario)'),
    sa.Column('reported_order_id', sa.Integer(), nullable=True, comment='Llave foránea a orders (si se reporta una orden)'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='Razón o motivo del reporte'),
    sa.Column('details', sa.Text(), nullable=True, comment='Detalles adicionales opcionales sobre el reporte'),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='moderation_status_enum'), server_default=sa.text("'PENDING'"), nullable=False, comment='Estado de moderación del reporte'),
    sa.Column('resolved_by_admin_id', sa.UUID(), nullable=True, comment='UUID del admin que resolvió el reporte'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['reported_listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la review'),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='Llave foranea UNIQUE a order_items'),
    sa.Column('buyer_id', sa.UUID(), nullable=False, comment='UUID del comprador'),
    sa.Column('seller_id', sa.UUID(), nullable=False, comment='UUID del vendedor'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Llave foranea a listings'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Calificación de la review (1 a 5 estrellas)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Texto opcional que acompaña la review'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_check'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('reports')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index('ix_offers_seller_status', table_name='offers')
    op.drop_index(op.f('ix_offers_seller_id'), table_name='offers')
    op.drop_index('ix_offers_listing_status', table_name='offers')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index('ix_offers_buyer_status', table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_table('listing_shipping_options')
    op.drop_index('ix_listing_images_listing_primary', table_name='listing_images', postgresql_where='is_primary = true')
    op.drop_index(op.f('ix_listing_images_listing_id'), table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index(op.f('ix_cart_items_listing_id'), table_name='cart_items')
    op.drop_index('ix_cart_items_cart_listing', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_payment_transactions_user_status', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_subscription_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_gateway_status', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_gateway'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_created', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_listings_type_status', table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index('ix_listings_seller_status', table_name='listings')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_index('ix_listings_price', table_name='listings')
    op.drop_index(op.f('ix_listings_listing_type'), table_name='listings')
    op.drop_index('ix_listings_category_status', table_name='listings')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('shipping_methods')
    op.drop_index(op.f('ix_payment_customers_user_id'), table_name='payment_customers')
    op.drop_index('ix_payment_customers_user_gateway', table_name='payment_customers')
    op.drop_table('payment_customers')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_buyer_status', table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_table('admin_action_logs')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('legal_documents')
    op.drop_table('faq_items')
    op.drop_index('ix_categories_type_parent', table_name='categories')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index('ix_categories_name_type', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
