"""migrate_user_foreign_keys_to_uuid

Revision ID: e6d7ed9c7b28
Revises: 1987c48e4769
Create Date: 2025-11-06 10:14:35.460112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d7ed9c7b28'
down_revision: Union[str, None] = '1987c48e4769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario propietario (NULL para direcciones de listings sin usuario)',
               existing_comment='Usuario propietario (NULL para direcciones de listings sin usuario)',
               existing_nullable=True)
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario propietario del carrito (relación 1:1)',
               existing_comment='Usuario propietario del carrito (relación 1:1)',
               existing_nullable=False)
    op.alter_column('listings', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario vendedor que creó esta publicación',
               existing_comment='ID del usuario vendedor que creó esta publicación',
               existing_nullable=False)
    op.alter_column('listings', 'approved_by_admin_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del administrador que aprobó la publicación',
               existing_comment='ID del administrador que aprobó la publicación',
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario que recibe la notificación',
               existing_comment='ID del usuario que recibe la notificación',
               existing_nullable=False)
    op.alter_column('offers', 'buyer_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario comprador que envía la oferta',
               existing_comment='ID del usuario comprador que envía la oferta',
               existing_nullable=False)
    op.alter_column('offers', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario vendedor que recibe la oferta',
               existing_comment='ID del usuario vendedor que recibe la oferta',
               existing_nullable=False)
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario comprador que realizó la orden',
               existing_comment='ID del usuario comprador que realizó la orden',
               existing_nullable=False)
    op.alter_column('reports', 'reporter_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario que reporta',
               existing_comment='Llave foránea a users (usuario que reporta)',
               existing_nullable=False)
    op.alter_column('reports', 'reported_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del usuario reportado (si se reporta un usuario)',
               existing_comment='Llave foránea a users (si se reporta un usuario)',
               existing_nullable=True)
    op.alter_column('reports', 'resolved_by_admin_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del admin que resolvió el reporte',
               existing_comment='Llave foránea a users (admin que resolvió el reporte)',
               existing_nullable=True)
    op.alter_column('reviews', 'buyer_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del comprador',
               existing_comment='Llave foranea a users (comprador)',
               existing_nullable=False)
    op.alter_column('reviews', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='UUID del vendedor',
               existing_comment='Llave foranea a users (vendedor)',
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.UUID(),
               comment='UUID del usuario (cognito sub claim)',
               existing_comment='Identificador único del usuario',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_column('users', 'cognito_sub')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_sub', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Sub (Subject) de Cognito para vincular con el servicio de autenticación'))
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.UUID(),
               server_default=sa.text("nextval('users_user_id_seq'::regclass)"),
               type_=sa.INTEGER(),
               comment='Identificador único del usuario',
               existing_comment='UUID del usuario (cognito sub claim)',
               existing_nullable=False)
    op.alter_column('reviews', 'seller_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Llave foranea a users (vendedor)',
               existing_comment='UUID del vendedor',
               existing_nullable=False)
    op.alter_column('reviews', 'buyer_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Llave foranea a users (comprador)',
               existing_comment='UUID del comprador',
               existing_nullable=False)
    op.alter_column('reports', 'resolved_by_admin_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Llave foránea a users (admin que resolvió el reporte)',
               existing_comment='UUID del admin que resolvió el reporte',
               existing_nullable=True)
    op.alter_column('reports', 'reported_user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Llave foránea a users (si se reporta un usuario)',
               existing_comment='UUID del usuario reportado (si se reporta un usuario)',
               existing_nullable=True)
    op.alter_column('reports', 'reporter_user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Llave foránea a users (usuario que reporta)',
               existing_comment='UUID del usuario que reporta',
               existing_nullable=False)
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del usuario comprador que realizó la orden',
               existing_comment='UUID del usuario comprador que realizó la orden',
               existing_nullable=False)
    op.alter_column('offers', 'seller_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del usuario vendedor que recibe la oferta',
               existing_comment='UUID del usuario vendedor que recibe la oferta',
               existing_nullable=False)
    op.alter_column('offers', 'buyer_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del usuario comprador que envía la oferta',
               existing_comment='UUID del usuario comprador que envía la oferta',
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del usuario que recibe la notificación',
               existing_comment='UUID del usuario que recibe la notificación',
               existing_nullable=False)
    op.alter_column('listings', 'approved_by_admin_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del administrador que aprobó la publicación',
               existing_comment='UUID del administrador que aprobó la publicación',
               existing_nullable=True)
    op.alter_column('listings', 'seller_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID del usuario vendedor que creó esta publicación',
               existing_comment='UUID del usuario vendedor que creó esta publicación',
               existing_nullable=False)
    op.alter_column('carts', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Usuario propietario del carrito (relación 1:1)',
               existing_comment='UUID del usuario propietario del carrito (relación 1:1)',
               existing_nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Usuario propietario (NULL para direcciones de listings sin usuario)',
               existing_comment='UUID del usuario propietario (NULL para direcciones de listings sin usuario)',
               existing_nullable=True)
    # ### end Alembic commands ###
