"""Initial migration: create all tables

Revision ID: f22e719cc9f5
Revises: 
Create Date: 2025-11-03 23:22:44.660822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22e719cc9f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la categoría'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre visible de la categoría'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identificador único legible en URLs'),
    sa.Column('type', sa.Enum('MATERIAL', 'PRODUCT', name='listing_type_enum', create_constraint=True), nullable=False, comment='Tipo de categoría: MATERIAL o PRODUCT'),
    sa.Column('parent_category_id', sa.Integer(), nullable=True, comment='ID de categoría padre para jerarquías'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('ix_categories_name_type', 'categories', ['name', 'type'], unique=True)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_categories_type'), 'categories', ['type'], unique=False)
    op.create_index('ix_categories_type_parent', 'categories', ['type', 'parent_category_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del usuario'),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False, comment='Sub (Subject) de Cognito para vincular con el servicio de autenticación'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Correo electrónico del usuario (debe ser normalizado)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Nombre completo o visible del usuario'),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role_enum', create_constraint=True), nullable=False, comment='Rol del usuario en la plataforma'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', name='user_status_enum', create_constraint=True), nullable=False, comment='Estado actual del usuario'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_cognito_sub'), 'users', ['cognito_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('listings',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la publicación'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='ID del usuario vendedor que creó esta publicación'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='ID de la categoría a la que pertenece'),
    sa.Column('listing_type', sa.Enum('MATERIAL', 'PRODUCT', name='listing_type_enum'), nullable=False, comment='Tipo de publicación: MATERIAL (B2B) o PRODUCT (B2C)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Título visible de la publicación'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descripción detallada del material o producto'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio monetario del ítem (precisión de 2 decimales)'),
    sa.Column('price_unit', sa.String(length=50), nullable=True, comment="Unidad de precio (ej. 'Kg', 'Tonelada', 'Unidad', 'Lote')"),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad disponible en inventario (stock)'),
    sa.Column('origin_description', sa.Text(), nullable=True, comment='Descripción del origen reciclado o reutilizado del material'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'INACTIVE', name='listing_status_enum', create_constraint=True), nullable=False, comment='Estado de moderación: PENDING, ACTIVE, REJECTED, INACTIVE'),
    sa.Column('approved_by_admin_id', sa.Integer(), nullable=True, comment='ID del administrador que aprobó la publicación'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_index('ix_listings_category_status', 'listings', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_listings_listing_type'), 'listings', ['listing_type'], unique=False)
    op.create_index('ix_listings_price', 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_index('ix_listings_seller_status', 'listings', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index('ix_listings_type_status', 'listings', ['listing_type', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la orden'),
    sa.Column('buyer_id', sa.Integer(), nullable=False, comment='ID del usuario comprador que realizó la orden'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Suma de los precios de todos los items sin comisión (precisión de 2 decimales)'),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Comisión de la plataforma, 10% del subtotal (precisión de 2 decimales)'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto total pagado: subtotal + commission_amount (precisión de 2 decimales)'),
    sa.Column('order_status', sa.Enum('PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status_enum', create_constraint=True), nullable=False, comment='Estado actual de la orden: PAID, SHIPPED, DELIVERED, CANCELLED, REFUNDED'),
    sa.Column('payment_charge_id', sa.String(length=255), nullable=True, comment='ID de la transacción en la pasarela de pago (Stripe/PayPal)'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment="Método de pago utilizado: 'stripe' o 'paypal'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('payment_charge_id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index('ix_orders_buyer_status', 'orders', ['buyer_id', 'order_status'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_table('listing_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la imagen'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='ID de la publicación a la que pertenece esta imagen'),
    sa.Column('image_url', sa.String(length=512), nullable=False, comment='URL completa y pública del objeto en el bucket S3'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Indica si esta es la imagen principal/portada del listing'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('image_url')
    )
    op.create_index(op.f('ix_listing_images_listing_id'), 'listing_images', ['listing_id'], unique=False)
    op.create_index('ix_listing_images_listing_primary', 'listing_images', ['listing_id', 'is_primary'], unique=True, postgresql_where='is_primary = true')
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único del ítem de la orden'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='ID de la orden a la que pertenece este ítem'),
    sa.Column('listing_id', sa.Integer(), nullable=True, comment='ID del listing (producto/material) asociado. Nulo si el listing fue eliminado.'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Cantidad del ítem comprado'),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio unitario del ítem en el momento de la compra (precisión de 2 decimales)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único de la review'),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='Llave foranea UNIQUE a order_items'),
    sa.Column('buyer_id', sa.Integer(), nullable=False, comment='Llave foranea a users (comprador)'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='Llave foranea a users (vendedor)'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Llave foranea a listings'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Calificación de la review (1 a 5 estrellas)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Texto opcional que acompaña la review'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creacion del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la ultima actualizacion del registro'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_check'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_listing_images_listing_primary', table_name='listing_images', postgresql_where='is_primary = true')
    op.drop_index(op.f('ix_listing_images_listing_id'), table_name='listing_images')
    op.drop_table('listing_images')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_buyer_status', table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_listings_type_status', table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index('ix_listings_seller_status', table_name='listings')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_index('ix_listings_price', table_name='listings')
    op.drop_index(op.f('ix_listings_listing_type'), table_name='listings')
    op.drop_index('ix_listings_category_status', table_name='listings')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cognito_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_categories_type_parent', table_name='categories')
    op.drop_index(op.f('ix_categories_type'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index('ix_categories_name_type', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
